export const sizes = {
  sm: {
    width: "w-12",
    height: "h-6",
    circle: "w-5 h-5",
    icon: 12,
    translateX: "translate-x-6",
    translateXNeg: "-translate-x-6",
    containerWidth: 48,
    containerHeight: 24,
    knobSize: 20,
    padding: 2,
  },
  md: {
    width: "w-16",
    height: "h-8",
    circle: "w-7 h-7",
    icon: 16,
    translateX: "translate-x-8",
    translateXNeg: "-translate-x-8",
    containerWidth: 64,
    containerHeight: 32,
    knobSize: 28,
    padding: 2,
  },
  lg: {
    width: "w-20",
    height: "h-10",
    circle: "w-9 h-9",
    icon: 20,
    translateX: "translate-x-10",
    translateXNeg: "-translate-x-10",
    containerWidth: 80,
    containerHeight: 40,
    knobSize: 36,
    padding: 3,
  },
};
